### Get all examples
GET http://localhost:3000/api/examples
Content-Type: application/json

### Get first example
GET http://localhost:3000/api/examples/1
Content-Type: application/json

### Create example
POST http://localhost:3000/api/examples
Content-Type: application/json

{
    "name": "New example",
    "description": "New example description"
}

### Create invalid example
POST http://localhost:3000/api/examples
Content-Type: application/json

{
    "description": "New example description"
}

### Change example #3
PUT http://localhost:3000/api/examples/3
Content-Type: application/json

{
    "name": "Changed example",
    "description": "Changed example description"
}

### Delete example #3
DELETE http://localhost:3000/api/examples/3
Content-Type: application/json


### Not found json request
GET http://localhost:3000/api/asdsd
Content-Type: application/json


### Not found http request
GET http://localhost:3000/asdsd
