GET http://localhost:5000/api/users/1

###


### Send POST request with json body
POST http://localhost:5000/api/users/1
Content-Type: application/json

{
    "country": "Russia",
    "city": "SPb"
}
