GET http://localhost:5000/api/users/1
Content-Type: application/json

###


### Send POST request with json body
POST http://localhost:5000/api/users/1
Content-Type: application/json

{
    "name": "Russia",
    "description": "SPb"
}

### Send invalid json request
GET http://localhost:5000/api/asdsd
Content-Type: application/json


### Send invalid request
GET http://localhost:5000/asdsd
